namespace UI3
{
    partial class MainWindow
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.mainLayout = new System.Windows.Forms.TableLayoutPanel();
            this.dot = new System.Windows.Forms.Button();
            this.button0 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.button5 = new System.Windows.Forms.Button();
            this.button6 = new System.Windows.Forms.Button();
            this.button7 = new System.Windows.Forms.Button();
            this.button8 = new System.Windows.Forms.Button();
            this.button9 = new System.Windows.Forms.Button();
            this.buttonDelete = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.divideButton = new System.Windows.Forms.Button();
            this.multiplyButton = new System.Windows.Forms.Button();
            this.addButton = new System.Windows.Forms.Button();
            this.sustractButton = new System.Windows.Forms.Button();
            this.buttonDeleteAll = new System.Windows.Forms.Button();
            this.equalsButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.mainLayout.SuspendLayout();
            this.SuspendLayout();
            this.mainLayout.AutoSize = true;
            this.mainLayout.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.mainLayout.ColumnCount = 4;
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.mainLayout.Controls.Add(this.dot, 0, 5);
            this.mainLayout.Controls.Add(this.button0, 1, 5);
            this.mainLayout.Controls.Add(this.button4, 0, 3);
            this.mainLayout.Controls.Add(this.button5, 1, 3);
            this.mainLayout.Controls.Add(this.button6, 2, 3);
            this.mainLayout.Controls.Add(this.button7, 0, 2);
            this.mainLayout.Controls.Add(this.button8, 1, 2);
            this.mainLayout.Controls.Add(this.button9, 2, 2);
            this.mainLayout.Controls.Add(this.buttonDelete, 0, 1);
            this.mainLayout.Controls.Add(this.button1, 0, 4);
            this.mainLayout.Controls.Add(this.button2, 1, 4);
            this.mainLayout.Controls.Add(this.button3, 2, 4);
            this.mainLayout.Controls.Add(this.divideButton, 3, 1);
            this.mainLayout.Controls.Add(this.multiplyButton, 3, 2);
            this.mainLayout.Controls.Add(this.addButton, 3, 3);
            this.mainLayout.Controls.Add(this.sustractButton, 3, 4);
            this.mainLayout.Controls.Add(this.buttonDeleteAll, 1, 1);
            this.mainLayout.Controls.Add(this.equalsButton, 2, 5);
            this.mainLayout.Controls.Add(this.label1, 0, 0);
            this.mainLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainLayout.Location = new System.Drawing.Point(0, 0);
            this.mainLayout.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.RowCount = 6;
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.mainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 54F));
            this.mainLayout.Size = new System.Drawing.Size(349, 524);
            this.mainLayout.TabIndex = 0;
            this.dot.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.dot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dot.FlatAppearance.BorderSize = 0;
            this.dot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dot.Location = new System.Drawing.Point(8, 443);
            this.dot.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.dot.Name = "dot";
            this.dot.Size = new System.Drawing.Size(71, 73);
            this.dot.TabIndex = 0;
            this.dot.Text = ".";
            this.dot.UseVisualStyleBackColor = false;
            this.dot.Click += new System.EventHandler(this.dot_Click);
            this.button0.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button0.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button0.FlatAppearance.BorderSize = 0;
            this.button0.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button0.Location = new System.Drawing.Point(95, 443);
            this.button0.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button0.Name = "button0";
            this.button0.Size = new System.Drawing.Size(71, 73);
            this.button0.TabIndex = 0;
            this.button0.Text = "0";
            this.button0.UseVisualStyleBackColor = false;
            this.button0.Click += new System.EventHandler(this.button0_Click);
            this.button4.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button4.FlatAppearance.BorderSize = 0;
            this.button4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button4.Location = new System.Drawing.Point(8, 269);
            this.button4.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(71, 71);
            this.button4.TabIndex = 0;
            this.button4.Text = "4";
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            this.button5.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button5.FlatAppearance.BorderSize = 0;
            this.button5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button5.Location = new System.Drawing.Point(95, 269);
            this.button5.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(71, 71);
            this.button5.TabIndex = 0;
            this.button5.Text = "5";
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            this.button6.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button6.FlatAppearance.BorderSize = 0;
            this.button6.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button6.Location = new System.Drawing.Point(182, 269);
            this.button6.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(71, 71);
            this.button6.TabIndex = 0;
            this.button6.Text = "6";
            this.button6.UseVisualStyleBackColor = false;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            this.button7.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button7.FlatAppearance.BorderSize = 0;
            this.button7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button7.Location = new System.Drawing.Point(8, 182);
            this.button7.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(71, 71);
            this.button7.TabIndex = 0;
            this.button7.Text = "7";
            this.button7.UseVisualStyleBackColor = false;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            this.button8.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button8.FlatAppearance.BorderSize = 0;
            this.button8.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button8.Location = new System.Drawing.Point(95, 182);
            this.button8.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(71, 71);
            this.button8.TabIndex = 0;
            this.button8.Text = "8";
            this.button8.UseVisualStyleBackColor = false;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            this.button9.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button9.FlatAppearance.BorderSize = 0;
            this.button9.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button9.Location = new System.Drawing.Point(182, 182);
            this.button9.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button9.Name = "button9";
            this.button9.Size = new System.Drawing.Size(71, 71);
            this.button9.TabIndex = 0;
            this.button9.Text = "9";
            this.button9.UseVisualStyleBackColor = false;
            this.button9.Click += new System.EventHandler(this.button9_Click);
            this.buttonDelete.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.buttonDelete.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonDelete.FlatAppearance.BorderSize = 0;
            this.buttonDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonDelete.Location = new System.Drawing.Point(8, 95);
            this.buttonDelete.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.buttonDelete.Name = "buttonDelete";
            this.buttonDelete.Size = new System.Drawing.Size(71, 71);
            this.buttonDelete.TabIndex = 0;
            this.buttonDelete.Text = "C";
            this.buttonDelete.UseVisualStyleBackColor = false;
            this.button1.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Location = new System.Drawing.Point(8, 356);
            this.button1.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(71, 71);
            this.button1.TabIndex = 0;
            this.button1.Text = "1";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.button2.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button2.FlatAppearance.BorderSize = 0;
            this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button2.Location = new System.Drawing.Point(95, 356);
            this.button2.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(71, 71);
            this.button2.TabIndex = 0;
            this.button2.Text = "2";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            this.button3.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.button3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.button3.FlatAppearance.BorderSize = 0;
            this.button3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button3.Location = new System.Drawing.Point(182, 356);
            this.button3.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(71, 71);
            this.button3.TabIndex = 0;
            this.button3.Text = "3";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            this.divideButton.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.divideButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.divideButton.FlatAppearance.BorderSize = 0;
            this.divideButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.divideButton.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.divideButton.Location = new System.Drawing.Point(269, 95);
            this.divideButton.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.divideButton.Name = "divideButton";
            this.divideButton.Size = new System.Drawing.Size(72, 71);
            this.divideButton.TabIndex = 0;
            this.divideButton.Text = "/";
            this.divideButton.UseVisualStyleBackColor = false;
            this.divideButton.Click += new System.EventHandler(this.divideButton_Click);
            this.multiplyButton.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.multiplyButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.multiplyButton.FlatAppearance.BorderSize = 0;
            this.multiplyButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.multiplyButton.Location = new System.Drawing.Point(269, 182);
            this.multiplyButton.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.multiplyButton.Name = "multiplyButton";
            this.multiplyButton.Size = new System.Drawing.Size(72, 71);
            this.multiplyButton.TabIndex = 0;
            this.multiplyButton.Text = "X";
            this.multiplyButton.UseVisualStyleBackColor = false;
            this.multiplyButton.Click += new System.EventHandler(this.MultiplyButton_Click);
            this.addButton.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.addButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.addButton.FlatAppearance.BorderSize = 0;
            this.addButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.addButton.Location = new System.Drawing.Point(269, 269);
            this.addButton.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.addButton.Name = "addButton";
            this.addButton.Size = new System.Drawing.Size(72, 71);
            this.addButton.TabIndex = 0;
            this.addButton.Text = "+";
            this.addButton.UseVisualStyleBackColor = false;
            this.addButton.Click += new System.EventHandler(this.addButton_Click);
            this.sustractButton.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.sustractButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sustractButton.FlatAppearance.BorderSize = 0;
            this.sustractButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.sustractButton.Location = new System.Drawing.Point(269, 356);
            this.sustractButton.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.sustractButton.Name = "sustractButton";
            this.sustractButton.Size = new System.Drawing.Size(72, 71);
            this.sustractButton.TabIndex = 0;
            this.sustractButton.Text = "-";
            this.sustractButton.UseVisualStyleBackColor = false;
            this.sustractButton.Click += new System.EventHandler(this.sustractButton_Click);
            this.buttonDeleteAll.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.mainLayout.SetColumnSpan(this.buttonDeleteAll, 2);
            this.buttonDeleteAll.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonDeleteAll.FlatAppearance.BorderSize = 0;
            this.buttonDeleteAll.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonDeleteAll.Location = new System.Drawing.Point(95, 95);
            this.buttonDeleteAll.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.buttonDeleteAll.Name = "buttonDeleteAll";
            this.buttonDeleteAll.Size = new System.Drawing.Size(158, 71);
            this.buttonDeleteAll.TabIndex = 0;
            this.buttonDeleteAll.Text = "CE";
            this.buttonDeleteAll.UseVisualStyleBackColor = false;
            this.equalsButton.BackColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.mainLayout.SetColumnSpan(this.equalsButton, 2);
            this.equalsButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.equalsButton.FlatAppearance.BorderSize = 0;
            this.equalsButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.equalsButton.Location = new System.Drawing.Point(182, 443);
            this.equalsButton.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.equalsButton.Name = "equalsButton";
            this.equalsButton.Size = new System.Drawing.Size(159, 73);
            this.equalsButton.TabIndex = 0;
            this.equalsButton.Text = "=";
            this.equalsButton.UseVisualStyleBackColor = false;
            this.equalsButton.Click += new System.EventHandler(this.equalsButton_Click);
            this.mainLayout.SetColumnSpan(this.label1, 4);
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("Consolas", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label1.Location = new System.Drawing.Point(8, 0);
            this.label1.Margin = new System.Windows.Forms.Padding(8, 0, 8, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(333, 87);
            this.label1.TabIndex = 1;
            this.label1.Text = "0";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AutoScaleDimensions = new System.Drawing.SizeF(20F, 43F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.ClientSize = new System.Drawing.Size(349, 524);
            this.Controls.Add(this.mainLayout);
            this.Font = new System.Drawing.Font("Consolas", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.Margin = new System.Windows.Forms.Padding(8, 8, 8, 8);
            this.Name = "MainWindow";
            this.Text = "Form1";
            this.mainLayout.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.Button addButton;
        private System.Windows.Forms.Button button0;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button buttonDelete;
        private System.Windows.Forms.Button buttonDeleteAll;
        private System.Windows.Forms.Button divideButton;
        private System.Windows.Forms.Button dot;
        private System.Windows.Forms.Button equalsButton;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TableLayoutPanel mainLayout;
        private System.Windows.Forms.Button multiplyButton;
        private System.Windows.Forms.Button sustractButton;

        #endregion
    }
}